deployment:
  tasks:
    - export DEPLOYPATH=/home/vwpdxpmh/public_html
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R pages $DEPLOYPATH
    - /bin/cp -R templates $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp .composer.json $DEPLOYPATH
    - /bin/cp .composer.lock $DEPLOYPATH
    - /bin/cp send_mail.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
   
